services:
  - type: web
    name: daulay-partners
    runtime: go
    rootDir: backend
    buildCommand: "cd ../frontend && npm install && npm run build && cd ../backend && go build -o server ."
    startCommand: ./server
    envVars:
      - key: GIN_MODE
        value: release
      - key: DATABASE_URL
        fromDatabase:
          name: daulay-db
          property: connectionString

databases:
  - name: daulay-db
    plan: free
    databaseName: daulay_partners
